### ISSUE TITLE
KeyPromoter Configuration missing when using IntelliJ 2016.1.1

### ISSUE THREAD

**Issue by ahus1** [athiele/key-promoter-fork#12]
I'm using IntelliJ 2016.1.1 and in the `File | Setting` I can't find a setting menu for KeyPromoter any more. 

I would still like to configure this plugin (time for flashing of the hints, and disable the popup to assign a hot key).

**Comment by athiele** [comment]
Hi, thanks for the bug report. I'll try to fix this issue - do you get any IDE exception concerning this?

**Comment by ahus1** [comment]
Unfortunately there is no exception in the log for it.

**Comment by athiele** [comment]
Fixed in version 2.0.2. It would be great if you could give me some feedback if everything works fine again.

**Comment by ahus1** [comment]
Thanks, working nicely again! I'm surproised that you reduced the size of the ZIP by half!

BTW: It would be nice if could update plugin.xml as well for upcoming releases, so people can check the version they have currently installed (both `<version />` and `<change-notes />`)

**Comment by ahus1** [comment]
... well, it is working in a way that the configuration menu is there, but the settings are not saved. 

Would you reopen the ticket? Should I file a new one?

**Comment by athiele** [comment]
Too bad - I reopen this then

**Comment by athiele** [comment]
Fixed in version 2.0.3 - Settings work again. However, the color settings cannot be persisted - something strange changed so that the awt.Color is not serialized properly any more. 

Please tell me if this release works for you.

**Comment by ahus1** [comment]
Thanks, this works great.
