### ISSUE TITLE
Incompatible with AS 2.2 RC 

### ISSUE THREAD

**Issue by suhas-sm** [athiele/key-promoter-fork#17]
Throws an error message while installing from disk. Says incompatible with this version of installation. Using AS 2.2 RC on OS X El Capitan.

**Comment by athiele** [comment]
Hi, Android Studio 2.2 is based on IntelliJ 2016.1.
http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html

So you need to install the release https://github.com/athiele/key-promoter-fork/releases/tag/2.0.4
which is compatible to IntelliJ 2016.1.
