### ISSUE TITLE
It does not show anything

### ISSUE THREAD

**Issue by mitoop** [athiele/key-promoter-fork#19]
The things goes that my PHPStorm version is 2016.2.1,after installing key-promoter(2.0.6 || 2.0.5),key-promoter doesn't show the `ugly` indication and top ten shows empty.

**Comment by athiele** [comment]
Hi there, I could not reproduce this with the latest version of KeyPromoter and PhpStorm. Please try to delete %HOME%\.PhpStorm2016.2\config\options\KeyPromoterStats.xml and restart PhpStorm.

**Comment by mitoop** [comment]
@athiele I reinstall,and it works.
