### ISSUE TITLE
Where is key promoter settings?

### ISSUE THREAD

**Issue by Aracki** [athiele/key-promoter-fork#24]
I have trouble finding those key promoter settings you are all talking about? 

I'm using _Key promoter version 2.0.7_ and _Intellij IDEA 2016.3_

All I have is Key Promoter Top Ten toolbar with refresh and reset statistics options.

**Comment by dkorobtsov** [comment]
@Aracki 
Key Promoter settings can be found in "Other Settings" section. Attaching screenshot.
![key_promoter](https://cloud.githubusercontent.com/assets/13999072/24081262/29ebe57e-0cb9-11e7-8bad-9c577abdb90f.PNG)

**Comment by Aracki** [comment]
Thanks a lot!
