### ISSUE TITLE
Release doesn't work with Java 6.0

### ISSUE THREAD

**Issue by carsten-wenderdel** [athiele/key-promoter-fork#8]
Hi Aimo,

I think persisting stats is a really good idea and I'd like to try your current release instead of the original key-promoter plugin.

Unfortunately as an AppCode user I'm stuck with Java 6.0 - this is because of some Intellij/Apple/Java issues. The plugin seems to be compiled for Java 7, I see the following error message when trying to run it:

com.intellij.diagnostic.PluginException: org/jetbrains/contest/keypromoter/KeyPromoter : Unsupported major.minor version 51.0 [Plugin: Key promoter]

So for future releases it would be really helpful if the byte code version could be set to 1.6

**Comment by athiele** [comment]
Hi Carsten,

thanks for your interest! I recompiled the jar with java 6 and replaced it. Please download it again and tell me if it works for you!

**Comment by carsten-wenderdel** [comment]
It works! (AppCode 3.1.2 / OS X 10.9.5 / Java 6.0)
Thanks a lot!
